# Created with YamlCreate.ps1 v2.1.3 using InputObject ðŸ¤– $debug=QUSU.7-2-6
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.2.0.schema.json

PackageIdentifier: Neovim.Neovim.Nightly
PackageVersion: 0.9.0
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: wix
Scope: machine
ReleaseDate: 2022-10-26
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.msi
  InstallerSha256: B486A89BA24B22D886C556DEFB2FA3E0959638D6FFEE430D518AB7E73DFA61DB
  ProductCode: '{6A1E88C4-3F1D-4995-BA8B-80D24A245AE6}'
ManifestType: installer
ManifestVersion: 1.2.0
